"""Build supabase/seed.sql and data/pokemon.json from the master Pokedex.xlsx.

Usage: python3 scripts/build_seed.py path/to/Pokedex.xlsx

Applies the data fixes approved in docs/DESIGN.md:
- empty text becomes NULL (dates, evolve_candy)
- text is trimmed
- Gender rows get dex_caught = TRUE
- columns renamed to snake_case; family_search is dropped (derived in the app)
"""
import datetime
import json
import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent

RENAME = {
    "ID": "id",
    "released_shiny": "release_shiny",
    "release event": "release_event",
    "how to get": "how_to_get",
}
DROP = {"family_search"}

# Corrections on top of the spreadsheet, by ID. Keep in sync with edits made in the database.
OVERRIDES = {
    "0774_fMETEOR_FORM": {"image_regular": "pm774.fMETEOR.icon.png", "image_shiny": "pm774.fMETEOR.s.icon.png"},
    "0150_fMEGA_X": {"released": "2026-05-25", "release_shiny": "2026-05-25"},
    "0150_fMEGA_Y": {"released": "2026-05-25", "release_shiny": "2026-05-25"},
}
DATE_COLS = {"released", "release_shiny", "release_shadow", "release_shadow_shiny",
             "release_dynamax", "release_dynamax_shiny"}
INT_COLS = {"species", "family", "stage", "evolve_candy"}
BOOL_COLS = {"dex_caught", "dex_lucky"}


def clean(col, v):
    if isinstance(v, str):
        v = v.strip()
        if v == "":
            return None
    if v is None:
        return None
    if col in DATE_COLS:
        if isinstance(v, datetime.datetime):
            return v.date().isoformat()
        raise ValueError(f"{col}: not a date: {v!r}")
    if col in INT_COLS:
        return int(v)
    if col in BOOL_COLS:
        return bool(v) if not isinstance(v, str) else v.upper() == "TRUE"
    if col == "gen_nr":
        return float(v) if float(v) != int(v) else int(v)
    return v


def sql(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def main(xlsx):
    wb = openpyxl.load_workbook(xlsx)

    gens = []
    rows = list(wb["gens"].iter_rows(values_only=True))
    for r in rows[1:]:
        if r[0] is None:
            continue
        gens.append({"gen_nr": clean("gen_nr", r[0]), "region": r[1].strip(), "prefix_name": r[2].strip()})

    rows = list(wb["pokemon"].iter_rows(values_only=True))
    header = [RENAME.get(h, h) for h in rows[0]]
    pokemon = []
    for i, r in enumerate(rows[1:], start=1):
        rec = {}
        for col, v in zip(header, r):
            if col in DROP:
                continue
            rec[col] = clean(col, v)
        if rec["form_type"] == "Gender":
            rec["dex_caught"] = True
        rec["sort_order"] = i
        rec.update(OVERRIDES.get(rec["id"], {}))
        pokemon.append(rec)

    ids = [p["id"] for p in pokemon]
    assert len(ids) == len(set(ids)), "duplicate IDs"

    # Split into parts small enough for the Supabase SQL editor. Rows are inserted without
    # evolves_from (babies point forward, e.g. Pikachu -> Pichu); the last part links evolutions.
    cols = [c for c in pokemon[0].keys() if c != "evolves_from"]
    head = "-- Generated by scripts/build_seed.py. Do not edit by hand. Run the parts in order."
    seed_dir = ROOT / "supabase" / "seed"
    seed_dir.mkdir(parents=True, exist_ok=True)
    for old in seed_dir.glob("*.sql"):
        old.unlink()

    def insert(chunk):
        return (f"insert into public.pokemon ({', '.join(cols)}) values\n"
                + ",\n".join("(" + ", ".join(sql(p[c]) for c in cols) + ")" for p in chunk) + ";")

    half = (len(pokemon) + 1) // 2
    part1 = [head, "begin;", "insert into public.gens (gen_nr, region, prefix_name) values",
             ",\n".join(f"({sql(g['gen_nr'])}, {sql(g['region'])}, {sql(g['prefix_name'])})" for g in gens) + ";"]
    part1 += [insert(pokemon[i:min(i + 200, half)]) for i in range(0, half, 200)]
    part1.append("commit;")
    part2 = [head, "begin;"] + [insert(pokemon[i:min(i + 200, len(pokemon))]) for i in range(half, len(pokemon), 200)] + ["commit;"]
    links = [p for p in pokemon if p["evolves_from"]]
    part3 = [head, "begin;", "alter table public.pokemon disable trigger pokemon_log_change;",
             "update public.pokemon p set evolves_from = v.f from (values\n"
             + ",\n".join(f"({sql(p['id'])}, {sql(p['evolves_from'])})" for p in links)
             + "\n) as v(id, f) where p.id = v.id;",
             "alter table public.pokemon enable trigger pokemon_log_change;", "commit;"]
    for n, part in enumerate([part1, part2, part3], start=1):
        (seed_dir / f"{n}.sql").write_text("\n".join(part) + "\n", encoding="utf-8")

    (ROOT / "data").mkdir(exist_ok=True)
    (ROOT / "data" / "pokemon.json").write_text(json.dumps(pokemon, ensure_ascii=False), encoding="utf-8")
    print(f"{len(gens)} gens, {len(pokemon)} pokemon written")


if __name__ == "__main__":
    main(sys.argv[1])
